services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    environment:
      - TZ=Asia/Karachi
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./ssl/jenkins.keystore:/var/jenkins_home/jenkins.keystore
    ports:
      - 8443:8443
    networks:
      - jenkinsnetwork
    command:
      - "--httpPort=-1"
      - "--httpsPort=8443"
      - "--httpsKeyStore=/var/jenkins_home/jenkins.keystore"
      - "--httpsKeyStorePassword=xzy123"

networks:
  jenkinsnetwork:
    driver: bridge
